[package]
name = "rust-clock-cli"
version = "0.1.0"
edition = "2024"
description = "A command line clock written in Rust."

[dependencies]
chrono = "0.4"
terminal_size = "0.4"
clap = { version = "4.5", features = ["derive"] }
